on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

name: Tests
jobs:
  entry_point_test:
    name: Entry Point Test - Python ${{ matrix.python_version }} - Featuretools ${{ matrix.featuretools_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9"]
        featuretools_version: ["Release", "Main"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Configure pip
        run: |
          pip config --site set global.progress_bar off
          pip install pip --upgrade
          pip install wheel
      - if: ${{ matrix.featuretools_version != 'Main' }}
        name: Install requirements
        run: pip install .
      - if: ${{ matrix.featuretools_version == 'Main' }}
        name: Install with latest version of Featuretools from main branch
        run: pip install . git+https://github.com/alteryx/featuretools.git@main#egg=featuretools
      - name: Verify installed packages have compatible dependencies
        run: pip check
      - name: Test entry point
        run: python -c "from featuretools import tsfresh"
