on:
  push:
    branches:    
      - circleci-scheduler

name: CircleCI Scheduler
jobs:
Featuretools:
  runs-on: ubuntu-latest
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
