on:
  push:
    branches:    
      - circleci-scheduler

name: CircleCI Scheduler
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
      run: |
        import os
        print(os.environ['PATH'])
      shell: python
  