on:
  push:
    branches:    
      - circleci-scheduler

name: CircleCI Scheduler
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - run: python my_script.py
      