on:
  push:
    branches:    
      - circleci-scheduler

name: CircleCI Scheduler
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
